[package]
name = "watchman"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

[dependencies]
anyhow = "1.0.75"
aws-config = "0.57.1"
aws-sdk-dynamodb = "0.35.0"
aws-sdk-ecs = "0.35.0"
aws-sdk-sesv2 = "0.35.0"
aws-smithy-types-convert = { version = "0.57.1", features = ["convert-chrono"] }
chrono = { version = "0.4.31", default-features = false, features = [
    "std",
    "clock",
    "serde",
] }
envy = "0.4.2"
lambda_runtime = "0.8.2"
medici-rust-shared = { git = "https://github.com/medici-uy/rust-shared" }
once_cell = "1.18.0"
reqwest = { version = "0.11.22", default-features = false, features = [
    "rustls-tls",
    "json",
] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }
url = { version = "2.4.1", features = ["serde"] }

[package.metadata.lambda.build.compiler]
type = "cargo"
