name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  ZIP_FILE: watchman.zip

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: cargo-lambda/cargo-lambda

      - uses: Swatinem/rust-cache@v2

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$(date +'%Y.%m.%d.%H.%M.%S')" \
            '${{ env.ZIP_FILE }}' \
            --latest
