name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-unknown-linux-gnu

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: cargo-lambda/cargo-lambda

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo lambda build --release --output-format zip

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$(date +'%Y.%m.%d.%H.%M.%S')" \
            target/lambda/sentinel/bootstrap.zip \
            --latest
